# Generated by Django 4.1 on 2022-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepies',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='initial_picture'),
        ),
    ]
